apiVersion: apps/v1
kind: Deployment 
metadata:
  name: deletetodo
spec:
  relicas: 1
  selector: 
    matchLabels: 
      app: deletetodo
  template: 
    metadata: 
      labels: 
        app: deletetodo
    spec:
      containers: 
      - name: deletetodo
        image: anjaliacr.azurecr.io/deletetodo:v1 
        ports: 
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:anjaliserver.database.windows.net,1433;Database=anjalidb;Uid=anjali;Pwd=#Kashmir@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
    